apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bookinfo
  namespace: demo-istio
spec:
  ingressClassName: nginx-istio
  host: bookinfo-istio.helloclouds.net
  upstreams:
  - name: productpage
    service: productpage
    port: 9080
    use-cluster-ip: true
  routes:
  - path: /
    action:
      proxy:
        upstream: productpage
        requestHeaders:
           set:
           - name: Host
             value: productpage.demo-istio.svc.cluster.local
