apiVersion: apps/v1
kind: Deployment
metadata:
   name: bash
   namespace: demo
spec:
  replicas: 1
  selector:
     matchLabels:
       app: bash
  template:
     metadata:
        labels:
          app: bash
        annotations:
          config.nsm.nginx.com/default-egress-allowed: "true"
     spec:
       containers:
       - name: bash
         image: curlimages/curl
         command: ["sleep", "600"]
