apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: target-internal-route
  namespace: legacy
  annotations:
    nsm.nginx.com/internal-route: "true"
spec:
  ingressClassName: nginx-nsm
  tls:
  rules:
  - host: legacy-svc.legacy
    http:
      paths:
      - path: /
        backend:
          serviceName: legacy-svc
          servicePort: 80
