apiVersion: specs.smi.nginx.com/v1alpha1
kind: RateLimit
metadata:
   name: backend-rate-limit
   namespace: testing
spec:
  destination:
     kind: Service
     name: ratelimit-backend
     namespace: testing
  sources:
  - kind: Deployment
    name: ratelimit-frontend
    namespace: testing
  name: 10rm
  rate: 10r/m
  burst: 0
  delay: nodelay
